### ISSUE TITLE
Add ability to save/serialise transaction for offline use

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/ark-net#11]
Add options to save transaction offline, i.e. create transaction and return serialised buffer that the users business application can store in their own way - with their security on top.

We would need to methods
- buffer transaction.export (Transaction)
- Transaction transaction.import(buffer)
- add test implementations

Ideally export would be called on already prepared payload (array of Transactions) - so the next step to send transaction is easy. Maybe both options

**Comment by sharkdev-j** [comment]
I'm not sure I am following this.  With the current API this is already possible using the TransactionApi.  Create a transaction using the TransactionApi which is an offline transaction.  The transaction can be saved as JSON using ToJson() on the TransactionApi.  Also the TransactionApi has FromJson() to convert it back.  The TransactionService already has PostTransaction with a TransactionApi.

Do we want to include wrapper methods in the AccountController to make it easier to use?  maybe something like CreateTransaction/SendTransaction methods that accept both TransactionApi and string json as parameters?

**Comment by kristjank** [comment]
> Do we want to include wrapper methods in the AccountController to make it easier to use? maybe something like CreateTransaction/SendTransaction methods that accept both TransactionApi and string json as parameters?

Yes exactly hits... as everyone starts with account controller.....
Also would add this to the documentation... readme.md after you have it... tnx
